version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.457.0
    - 1.464.0
    - 1.486.0
    - 1.491.0
    - 1.495.0
    - 1.503.0
    - 1.505.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.532.0
    - 1.563.0
    - 1.564.0
    - 1.566.0
    - 1.570.0
  - dependency-name: "@types/sharp"
    versions:
    - 0.27.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
  - dependency-name: sharp
    versions:
    - 0.28.0
  - dependency-name: sequelize
    versions:
    - 6.6.1
  - dependency-name: mongoose
    versions:
    - 5.11.18
    - 5.11.19
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: handlebars
    versions:
    - 4.7.7
