kind: pipeline
name: node16

steps:
  - name: test node 16
    image: node:16
    failure: ignore
    commands:
      - npm i
      - npm run test:lint
      - WAOS_NODE_db_uri='mongodb://mongo:27017/WaosNodeTest' npm run test
services:
  - name: mongo
    image: mongo:latest
